version: "2.0"
services:
  qbittorrent:
    image: nevinee/qbittorrent:4.3.8 # 如想参与测试工作可以指定nevinee/qbittorrent:unstable，如想使用集成了iyuu的版本请指定nevinee/qbittorrent:iyuu
    container_name: qbittorrent
    restart: always
    tty: true
    network_mode: host
    hostname: qbitorrent
    volumes:
      - /data1:/data1      # 配置保存目录
    tmpfs:
      - /tmp
    environment:          # 下面未列出的其他环境变量请根据环境变量清单自行添加
      - WEBUI_PORT=8080   # WEBUI控制端口，可自定义
      - BT_PORT=34567     # BT监听端口，可自定义
      - PUID=1000         # 输入id -u可查询，群晖必须改
      - PGID=100          # 输入id -g可查询，群晖必须改
    ports:
      - 8080:8080        # 冒号左右一致，必须同WEBUI_PORT一样，本文件中的3个8080要改一起改
      - 23837:23837      # 冒号左右一致，必须同BT_PORT一样，本文件中的5个34567要改一起改
      - 23837:23837/udp  # 冒号左右一致，必须同BT_PORT一样，本文件中的5个34567要改一起改