name: <your project name>
services:
    3x-ui:
        stdin_open: true
        tty: true
        environment:
            - XRAY_VMESS_AEAD_FORCED=false
        volumes:
            - ./db/:/etc/x-ui/
            - ./cert/:/root/cert/
        network_mode: host
        restart: unless-stopped
        container_name: 3x-ui
        image: ghcr.io/mhsanaei/3x-ui:latest

