version: '3.3'
services:
    x-ui:
        network_mode: host
        volumes:
            - '/home/docker/xui/db/:/etc/x-ui/'
            - '/home/docker/xui/cert/:/root/cert/'
        container_name: x-ui
        restart: unless-stopped
        image: enwaiax/x-ui

